"""init

Revision ID: 0a18af36477f
Revises: 
Create Date: 2025-05-14 23:15:02.066834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a18af36477f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('mdhash', sa.String(length=64), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mdhash')
    )
    op.create_index(op.f('ix_documents_file_path'), 'documents', ['file_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_path'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
